#!/usr/bin/bash
set -ex

export model=l  # n s m l x
MODEL_FILE="dfine_${model}_coco.pth"
MODEL_URL="https://github.com/Peterande/storage/releases/download/dfinev1.0/${MODEL_FILE}"

# Download model if not present
[ -f "$MODEL_FILE" ] || { echo Downloading ${MODEL_URL}...; wget -q "${MODEL_URL}"; }

# Run inference
python tools/inference/torch_inf.py -c configs/dfine/dfine_hgnetv2_${model}_coco.yml -r "$MODEL_FILE" --input tools/dataset/horse.jpg --device cuda:0
